name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Code analysis
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v
