name: Unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
      - name: Run tests
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          go install github.com/onsi/gomega/...
          ginkgo -r -v  --covermode=atomic --coverprofile=coverage.out -p -r ./...
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
